version: '2'

services:
  microtransactionmgtapi:
    container_name: microtransactionmgtapi
    image: petprojects/micro-transactions-mgt-api:${BUILD_VERSION}
    build:
      context: ./src/API
      dockerfile: Dockerfile
      args:
        source: ./build
  ci-integration-tests:
    image: microsoft/dotnet:2.0-sdk
    container_name: integrationtests
    volumes:
     - .:/src
    working_dir: /src
    environment:
     - ApiEndpoint=http://microtransactionsmgtapi/
    links:
     - microtransactionmgtapi
    command: sh ./deploy/scripts/run-integration-tests.sh
