version: '2'

services:
  microtransactionmgt:
    container_name: microtransactionmgt
    image: petprojects/micro-transactions-mgt:${BUILD_VERSION}
    build:
      context: ./src/API
      dockerfile: Dockerfile
      args:
        source: ./build
  ci-integration-tests:
    image: microsoft/dotnet:2.0-sdk
    container_name: integrationtests
    volumes:
     - .:/src
    working_dir: /src
    environment:
     - ApiEndpoint=http://microtransactionsmgt/
    links:
     - microtransactionmgt
    command: sh ./deploy/scripts/run-integration-tests.sh
