version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0
    container_name: build
    volumes:
     - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore MicroTransactionMgtApi.sln && dotnet publish MicroTransactionMgtApi.sln -c Release -o build"