version: '2'

services:
  microtransactionmgt:
    container_name: microtransactionmgt
    image: petprojects/micro-transactions-mgt:dev
    build:
      context: ./src/API
      dockerfile: Dockerfile
      args:
        source: ./build
    ports:
      - "5000:80"
